No package files given... Grabbing a set.
<<<          obj /usr/share/man/man3/talloc.3.bz2
<<<          obj /usr/lib64/pkgconfig/talloc.pc
<<<          obj /usr/lib64/pkgconfig/pytalloc-util.cpython-38-x86_64-linux-gnu.pc
<<<          obj /usr/lib64/libtalloc.so.2.3.1
<<<          sym /usr/lib64/libtalloc.so.2
<<<          sym /usr/lib64/libtalloc.so
<<<          obj /usr/lib64/libpytalloc-util.cpython-38-x86-64-linux-gnu.so.2.3.1
<<<          sym /usr/lib64/libpytalloc-util.cpython-38-x86-64-linux-gnu.so.2
<<<          sym /usr/lib64/libpytalloc-util.cpython-38-x86-64-linux-gnu.so
<<<          obj /usr/lib/python3.8/site-packages/talloc.cpython-38-x86_64-linux-gnu.so
<<<          obj /usr/include/x86_64-pc-linux-gnu/pytalloc.h
<<<          obj /usr/include/talloc.h
<<<          obj /usr/include/pytalloc.h
--- !empty   dir /usr/share/man/man3
--- !empty   dir /usr/share/man
--- !empty   dir /usr/share
--- !empty   dir /usr/lib64/pkgconfig
--- !empty   dir /usr/lib64
--- !empty   dir /usr/lib/python3.8/site-packages
--- !empty   dir /usr/lib/python3.8
--- !empty   dir /usr/lib
--- !empty   dir /usr/include/x86_64-pc-linux-gnu
--- !empty   dir /usr/include
--- !empty   dir /usr
>>> Regenerating /etc/ld.so.cache...
